name: Python build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: run black
        uses: psf/black@stable

  lint:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: install Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: run ruff
        run: ruff check --output-format=github .

  test:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.9.9"
      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"
      - name: Run unit tests
        run: uv run pytest --cov-report=term-missing --cov-append
